#!/bin/sh

# NOTE: I use the "scrot" command-line screenshot utility. If you wish to substitute a different command-line program such as ImageMagick, simply replace the entire command with your preferred tool.
WHL="Capture entire screen"
WIN="Capture focused window"
SEL="Capture selection of screen"
RES=$(printf "$WHL\n$WIN\n$SEL" | dmenu -p Screenshot:)

if [ x"$RES" = x"$WHL" ]; then
      scrot -e 'mv $f ~/Captures/' # Take a screenshot of the entire screen, and then move said screenshot to the "Captures" directory in user's home.
   elif [ x"$RES" = x"$WIN" ]; then
      scrot -ue 'mv $f ~/Captures/' # Take a screenshot of the currently-focused window, and then move said screenshot to the "Captures" directory in user's home.
   elif [ x"$RES" = x"$SEL" ]; then
      scrot -se 'mv $f ~/Captures/' # Take a screenshot of an area selected with the cursor, and then move said screenshot to the "Captures" directory in user's home.
   else
      exit 1
   fi
